In [2]:
import numpy as np
import pandas as pd
import scipy.io as sio
import matplotlib
import matplotlib.pyplot as plt
from numpy.matlib import repmat
from sklearn.preprocessing import normalize

%matplotlib inline

In [3]:
def eigsort(V, eigvals):
    
    # Sort the eigenvalues from largest to smallest. Store the sorted
    # eigenvalues in the column vector lambd.
    lohival = np.sort(eigvals)
    lohiindex = np.argsort(eigvals)
    lambd = np.flip(lohival)
    index = np.flip(lohiindex)
    Dsort = np.diag(lambd)
    
    # Sort eigenvectors to correspond to the ordered eigenvalues. Store sorted
    # eigenvectors as columns of the matrix vsort.
    M = np.size(lambd)
    Vsort = np.zeros((M, M))
    for i in range(M):
        Vsort[:,i] = V[:,index[i]]
    return Vsort, Dsort

In [7]:
df = pd.read_csv("encoded_smartphone_data.csv")

In [8]:
df

,Unnamed: 0,Brand,Model,Added,Width,Height,Depth,Volume,Band Count,RAM_TYPE_DDR SDRAM,...,"ProtectionFromLiquids_5 Protected against low pressure jets (all directions), limited ingress",ProtectionFromLiquids_6 Protection against powerful jets of water,ProtectionFromLiquids_7 Protected against immersion up to 1m of depth,ProtectionFromLiquids_8 Protected against immersion beyond 1m of depth,ProtectionFromLiquids_9 Protected against high temperature high pressure spray downs,ProtectionFromLiquids_Non-standard protection,ProtectionFromLiquids_Yes,DataIntegrity_Final,DataIntegrity_Incomplete,DataIntegrity_Preliminary
0,0,ZTE,Blade 20 Smart Global TD-LTE 128GB,1/1/2020 12:55,76.6,162.91,8.95,111686.20870,14,0,...,0,0,0,0,0,0,1,0,0,1
1,1,Samsung,SM-G6200 Galaxy A6s Dual SIM TD-LTE CN 128GB,11/7/2018 22:32,76.5,156.30,8.40,100438.38000,21,0,...,0,0,0,0,0,0,1,0,0,1
2,2,LG,LMV450VMB V50 ThinQ 5G TD-LTE US V450VMB,3/5/2019 23:31,76.1,159.20,8.30,100555.49600,20,0,...,0,0,0,1,0,0,0,1,0,0
3,3,Huawei,Y5 Lite 2018 Dual SIM LTE LATAM CAG-LX3 / CAG-L23,5/10/2018 20:11,73.7,145.10,9.45,101057.07150,12,0,...,0,0,0,0,0,0,1,0,0,1
4,4,Nokia,4.2 Dual SIM TD-LTE AM 32GB,8/14/2019 15:07,71.3,148.95,8.39,89102.93265,21,0,...,0,0,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13564,13938,Samsung,SGH-i780,9/22/2007 23:57,61.3,115.90,12.90,91650.24300,4,0,...,0,0,0,0,0,0,1,1,0,0
13565,13939,Vodafone,VPA Compact GPS,1/31/2007 13:51,58.2,108.00,18.40,115655.04000,7,0,...,0,0,0,0,0,0,1,1,0,0
13566,13940,E-TEN,InfoTouch P603,4/3/2005 18:03,82.0,137.40,18.40,207309.12000,3,0,...,0,0,0,0,0,0,1,1,0,0
13567,13941,Airis,T482,8/15/2008 18:05,62.0,125.00,14.00,108500.00000,4,0,...,0,0,0,0,0,0,1,1,0,0
13568,13942,Nokia,E62,11/26/2007 0:05,69.7,117.00,18.00,146788.20000,4,0,...,0,0,0,0,0,0,1,1,0,0

In [37]:
df.isnull().any().any()

False

In [85]:
try_mean = df.mean() #gets mean of every numerical column
try_mean.shape
# try_mean

(150,)

In [90]:
try_sample_mean = np.mean(df, axis=1)
try_sample_mean.shape
# try_sample_mean

(13569,)

In [43]:
# sample_mean = np.mean(df[4,:], axis = 1)
# sample_mean.shapeb
# sample_mean

TypeError: '(4, slice(None, None, None))' is an invalid key

In [104]:
try_sample_mean = try_sample_mean.T
try_sample_mean.shape
try_sample_mean

0         746.444458
1         671.463867
2         672.260640
3         675.455477
4         595.830484
            ...
13564     705.335620
13565     865.357600
13566    1476.719467
13567     817.760000
13568    1073.046000
Length: 13569, dtype: float64

In [113]:
df_series = pd.Series(try_sample_mean)
df_series
df_series.shape

(13569,)

In [117]:
reshape_mean = pd.DataFrame(df_series)
reshape_mean.shape
reshape_mean

                 0
0       746.444458
1       671.463867
2       672.260640
3       675.455477
4       595.830484
...            ...
13564   705.335620
13565   865.357600
13566  1476.719467
13567   817.760000
13568  1073.046000

[13569 rows x 1 columns]

In [112]:
try_reshape_mean = np.reshape(df_series, (13569, -1))

Exception: Data must be 1-dimensional

In [100]:
len(df_series)

13569